---
# Run sysbench test
- name:  Run sysbench random write RWO test
  block:
    - name:  Run sysbench random write RWO test
      k8s:
        state: present
        definition: "{{ lookup('template', 'sysbench_random_write_rwo.yaml.j2') }}"
        wait: yes
        wait_timeout: 7200
        wait_condition:
          type: Complete
          status: "True"

    - name: Get logs of the sysbench random write pod for RWO
      kubernetes.core.k8s_log:
        namespace: "{{ storage_perf_namespace }}"
        label_selectors:
        - job-name=sysbench-random-write-rwo
      register: logo

    - name: Save random write Log to local file
      local_action: 
        module: copy 
        content: "{{ logo }}"
        dest: "{{ logfolder }}/random_write_rwo.json"

  rescue:
    - debug:
        msg: 
         - "Run sysbench random write RWO test failed or timed out after 2 hours." 
         - "Please check your openshift storage configuration. This is likely due to poor I/O."
