---
# Run sysbench test
- name: Run sysbench sequential read RWX test
  block:
    - name:  Run sysbench sequential read RWX test
      k8s:
        state: present
        definition: "{{ lookup('template', 'sysbench_sequential_read_rwx.yaml.j2') }}"
        wait: yes
        wait_timeout: 7200
        wait_condition:
          type: Complete
          status: "True"

    - name: Get logs of the sysbench sequential read pod for RWX
      kubernetes.core.k8s_log:
        namespace: "{{ storage_perf_namespace }}"
        label_selectors:
        - job-name=sysbench-sequential-read-rwx
      register: logx

    - name: Save Log to local file
      local_action:
        module: copy
        content: "{{ logx }}"
        dest: "{{ logfolder }}/sequential_read_rwx.json"

  rescue:
    - debug:
        msg: 
         - "Run sysbench random write RWO test failed or timed out after 2 hours." 
         - "Please check your openshift storage configuration. This is likely due to poor I/O."